[package]
name = "bao-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
ouroboros = "0.15.6"
range-collections = "0.4.0"
smallvec = "1.10.0"
bytes = { version = "1.4.0" }
tokio = { version = "1.24.1", features = ["full"] }
futures = "0.3.27"
hex = "0.4.3"

[dev-dependencies]
hex = "0.4.3"
bao = "0.12.1"
# abao with chunk group size 16 (abao default)
abao = { git = "https://github.com/n0-computer/abao", branch = "post-order-outboard", features = ["group_size_1k"], default_features = false }
proptest = "1.0.0"
rand = "0.8.5"
tokio = "1.24.1"
