[package]
name = "bao-tree"
version = "0.1.3"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>"]
description = "BLAKE3 verfiied streaming with custom chunk groups and range set queries"
license = "MIT OR Apache-2.0"
repository = "https://github.com/n0-computer/bao-tree"
edition = "2021"
keywords = ["hashing"]
categories = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
range-collections = "0.4.0"
smallvec = "1"

ouroboros = { version = "0.15.6", optional = true }
bytes = { version = "1.4.0", optional = true }
tokio = { version = "1.24.1", features = ["full"], optional = true }
futures = { version = "0.3.27", optional = true }

[features]
tokio_io = ["tokio", "bytes", "futures", "ouroboros"]
default = ["tokio_io"]

[dev-dependencies]
hex = "0.4.3"
bao = "0.12.1"
tokio = { version = "1.24.1", features = ["full"] }
# abao with chunk group size 16 (abao default)
abao = { git = "https://github.com/n0-computer/abao", branch = "post-order-outboard", features = ["group_size_1k"], default_features = false }
proptest = "1.0.0"
rand = "0.8.5"
