[package]
name = "bao-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.3"
range-collections = "0.4.0"

[dev-dependencies]
hex = "0.4.3"
bao = "0.12.1"
abao = { git = "https://github.com/n0-computer/abao", branch = "post-order-outboard", features = ["group_size_1k"], default_features = false }
proptest = "1.0.0"
rand = "0.8.5"
tokio = "1.24.1"
