[package]
name = "bao-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bao = "0.12.1"
blake3 = "1.3.3"
hex = "0.4.3"
itertools = "0.10.5"
proptest = "1.0.0"
rand = "0.8.5"
tokio = "1.24.1"
